import { Effect } from "effect";

import { BuildProfileError } from "../lib/exit-codes";
import { printHuman } from "../lib/output";
import { isExpoUpdatesInstalled } from "../lib/update-channel-native";

import type { BuildProfile } from "../lib/build-profile";

/**
 * EAS parity: bake the profile's channel into the native app as the
 * expo-channel-name request header. Only apps shipping expo-updates read the
 * header — a binary built without it silently falls back to the server's
 * default channel, so a missing `channel` on an updates-enabled profile fails
 * fast instead. Returns the channel to inject, or `undefined` to skip.
 *
 * NOT gated on the build strategy, deliberately. This used to start with
 * `if (strategy !== "expo") return undefined;`, which meant every bare /
 * native / kmp / custom project shipping expo-updates got NO channel at all —
 * silently, with the binary then falling back to the server default, i.e.
 * exactly the failure this function's own docstring warns about. The channel
 * is a property of the BINARY, not of how the binary was produced:
 * expo-updates reads `requestHeaders["expo-channel-name"]` out of
 * AndroidManifest.xml / Expo.plist at runtime and does not care whether those
 * files were generated by prebuild or committed to the repo. A committed
 * `android/` is just as valid an injection target as a generated one.
 *
 * The one real prerequisite — expo-updates actually being installed — is
 * checked below and is unchanged.
 */
export const resolveUpdateChannel = (params: {
  readonly userCwd: string;
  readonly profile: BuildProfile;
}) =>
  Effect.gen(function* () {
    const { userCwd, profile } = params;
    if (!(yield* isExpoUpdatesInstalled(userCwd))) {
      yield* printHuman("expo-updates is not installed — skipping update-channel injection.");
      return undefined;
    }
    if (profile.channel === undefined) {
      return yield* new BuildProfileError({
        message: `Build profile "${profile.name}" has no "channel". The channel is baked into the binary as the expo-channel-name update request header; add e.g. "channel": "production" to the profile.`,
      });
    }
    return profile.channel;
  });
