-- Track whether a provisioning profile is ASC-managed (generated by us) vs
-- user-uploaded, plus the device roster hash embedded at generate time. The
-- build-credentials resolver regenerates managed AD_HOC/DEVELOPMENT profiles
-- when the current device set drifts from the stored hash; uploaded profiles
-- are never auto-regenerated.
--
-- is_managed defaults to 0 so pre-existing rows are treated as uploaded.
-- Pre-migration ASC-generated rows will need to be regenerated via the
-- dashboard once to opt in to automatic roster tracking.
ALTER TABLE "apple_provisioning_profiles" ADD COLUMN "is_managed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "apple_provisioning_profiles" ADD COLUMN "device_roster_hash" TEXT;
