/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CliLoginRouteImport } from './routes/cli-login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/_app/index'
import { Route as AuthedAppMembersRouteImport } from './routes/_authed/_app/members'
import { Route as AuthedAppCredentialsRouteImport } from './routes/_authed/_app/credentials'
import { Route as AuthedAppAuditLogRouteImport } from './routes/_authed/_app/audit-log'
import { Route as AuthedAppApiKeysRouteImport } from './routes/_authed/_app/api-keys'
import { Route as AuthedAppSettingsIndexRouteImport } from './routes/_authed/_app/settings/index'
import { Route as AuthedAppProjectsIndexRouteImport } from './routes/_authed/_app/projects/index'
import { Route as AuthedAppAccountIndexRouteImport } from './routes/_authed/_app/account/index'
import { Route as AuthedAppProjectsProjectIdRouteImport } from './routes/_authed/_app/projects/$projectId'
import { Route as AuthedAppProjectsProjectIdIndexRouteImport } from './routes/_authed/_app/projects/$projectId/index'
import { Route as AuthedAppProjectsProjectIdUpdatesIndexRouteImport } from './routes/_authed/_app/projects/$projectId/updates/index'
import { Route as AuthedAppProjectsProjectIdSettingsIndexRouteImport } from './routes/_authed/_app/projects/$projectId/settings/index'
import { Route as AuthedAppProjectsProjectIdEnvironmentVariablesIndexRouteImport } from './routes/_authed/_app/projects/$projectId/environment-variables/index'
import { Route as AuthedAppProjectsProjectIdChannelsIndexRouteImport } from './routes/_authed/_app/projects/$projectId/channels/index'
import { Route as AuthedAppProjectsProjectIdBuildsIndexRouteImport } from './routes/_authed/_app/projects/$projectId/builds/index'
import { Route as AuthedAppProjectsProjectIdBranchesIndexRouteImport } from './routes/_authed/_app/projects/$projectId/branches/index'
import { Route as AuthedAppProjectsProjectIdChannelsChannelIdRouteImport } from './routes/_authed/_app/projects/$projectId/channels/$channelId'
import { Route as AuthedAppProjectsProjectIdBuildsBuildIdRouteImport } from './routes/_authed/_app/projects/$projectId/builds/$buildId'

const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli-login',
  path: '/cli-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppMembersRoute = AuthedAppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppCredentialsRoute = AuthedAppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppAuditLogRoute = AuthedAppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppApiKeysRoute = AuthedAppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSettingsIndexRoute = AuthedAppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppProjectsIndexRoute = AuthedAppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppAccountIndexRoute = AuthedAppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppProjectsProjectIdRoute =
  AuthedAppProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppProjectsProjectIdIndexRoute =
  AuthedAppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)
const AuthedAppProjectsProjectIdUpdatesIndexRoute =
  AuthedAppProjectsProjectIdUpdatesIndexRouteImport.update({
    id: '/updates/',
    path: '/updates/',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)
const AuthedAppProjectsProjectIdSettingsIndexRoute =
  AuthedAppProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)
const AuthedAppProjectsProjectIdEnvironmentVariablesIndexRoute =
  AuthedAppProjectsProjectIdEnvironmentVariablesIndexRouteImport.update({
    id: '/environment-variables/',
    path: '/environment-variables/',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)
const AuthedAppProjectsProjectIdChannelsIndexRoute =
  AuthedAppProjectsProjectIdChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)
const AuthedAppProjectsProjectIdBuildsIndexRoute =
  AuthedAppProjectsProjectIdBuildsIndexRouteImport.update({
    id: '/builds/',
    path: '/builds/',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)
const AuthedAppProjectsProjectIdBranchesIndexRoute =
  AuthedAppProjectsProjectIdBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)
const AuthedAppProjectsProjectIdChannelsChannelIdRoute =
  AuthedAppProjectsProjectIdChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)
const AuthedAppProjectsProjectIdBuildsBuildIdRoute =
  AuthedAppProjectsProjectIdBuildsBuildIdRouteImport.update({
    id: '/builds/$buildId',
    path: '/builds/$buildId',
    getParentRoute: () => AuthedAppProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedAppIndexRoute
  '/cli-login': typeof CliLoginRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/api-keys': typeof AuthedAppApiKeysRoute
  '/audit-log': typeof AuthedAppAuditLogRoute
  '/credentials': typeof AuthedAppCredentialsRoute
  '/members': typeof AuthedAppMembersRoute
  '/projects/$projectId': typeof AuthedAppProjectsProjectIdRouteWithChildren
  '/account/': typeof AuthedAppAccountIndexRoute
  '/projects/': typeof AuthedAppProjectsIndexRoute
  '/settings/': typeof AuthedAppSettingsIndexRoute
  '/projects/$projectId/': typeof AuthedAppProjectsProjectIdIndexRoute
  '/projects/$projectId/builds/$buildId': typeof AuthedAppProjectsProjectIdBuildsBuildIdRoute
  '/projects/$projectId/channels/$channelId': typeof AuthedAppProjectsProjectIdChannelsChannelIdRoute
  '/projects/$projectId/branches/': typeof AuthedAppProjectsProjectIdBranchesIndexRoute
  '/projects/$projectId/builds/': typeof AuthedAppProjectsProjectIdBuildsIndexRoute
  '/projects/$projectId/channels/': typeof AuthedAppProjectsProjectIdChannelsIndexRoute
  '/projects/$projectId/environment-variables/': typeof AuthedAppProjectsProjectIdEnvironmentVariablesIndexRoute
  '/projects/$projectId/settings/': typeof AuthedAppProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/updates/': typeof AuthedAppProjectsProjectIdUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedAppIndexRoute
  '/cli-login': typeof CliLoginRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/api-keys': typeof AuthedAppApiKeysRoute
  '/audit-log': typeof AuthedAppAuditLogRoute
  '/credentials': typeof AuthedAppCredentialsRoute
  '/members': typeof AuthedAppMembersRoute
  '/account': typeof AuthedAppAccountIndexRoute
  '/projects': typeof AuthedAppProjectsIndexRoute
  '/settings': typeof AuthedAppSettingsIndexRoute
  '/projects/$projectId': typeof AuthedAppProjectsProjectIdIndexRoute
  '/projects/$projectId/builds/$buildId': typeof AuthedAppProjectsProjectIdBuildsBuildIdRoute
  '/projects/$projectId/channels/$channelId': typeof AuthedAppProjectsProjectIdChannelsChannelIdRoute
  '/projects/$projectId/branches': typeof AuthedAppProjectsProjectIdBranchesIndexRoute
  '/projects/$projectId/builds': typeof AuthedAppProjectsProjectIdBuildsIndexRoute
  '/projects/$projectId/channels': typeof AuthedAppProjectsProjectIdChannelsIndexRoute
  '/projects/$projectId/environment-variables': typeof AuthedAppProjectsProjectIdEnvironmentVariablesIndexRoute
  '/projects/$projectId/settings': typeof AuthedAppProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/updates': typeof AuthedAppProjectsProjectIdUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/cli-login': typeof CliLoginRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/_app/api-keys': typeof AuthedAppApiKeysRoute
  '/_authed/_app/audit-log': typeof AuthedAppAuditLogRoute
  '/_authed/_app/credentials': typeof AuthedAppCredentialsRoute
  '/_authed/_app/members': typeof AuthedAppMembersRoute
  '/_authed/_app/': typeof AuthedAppIndexRoute
  '/_authed/_app/projects/$projectId': typeof AuthedAppProjectsProjectIdRouteWithChildren
  '/_authed/_app/account/': typeof AuthedAppAccountIndexRoute
  '/_authed/_app/projects/': typeof AuthedAppProjectsIndexRoute
  '/_authed/_app/settings/': typeof AuthedAppSettingsIndexRoute
  '/_authed/_app/projects/$projectId/': typeof AuthedAppProjectsProjectIdIndexRoute
  '/_authed/_app/projects/$projectId/builds/$buildId': typeof AuthedAppProjectsProjectIdBuildsBuildIdRoute
  '/_authed/_app/projects/$projectId/channels/$channelId': typeof AuthedAppProjectsProjectIdChannelsChannelIdRoute
  '/_authed/_app/projects/$projectId/branches/': typeof AuthedAppProjectsProjectIdBranchesIndexRoute
  '/_authed/_app/projects/$projectId/builds/': typeof AuthedAppProjectsProjectIdBuildsIndexRoute
  '/_authed/_app/projects/$projectId/channels/': typeof AuthedAppProjectsProjectIdChannelsIndexRoute
  '/_authed/_app/projects/$projectId/environment-variables/': typeof AuthedAppProjectsProjectIdEnvironmentVariablesIndexRoute
  '/_authed/_app/projects/$projectId/settings/': typeof AuthedAppProjectsProjectIdSettingsIndexRoute
  '/_authed/_app/projects/$projectId/updates/': typeof AuthedAppProjectsProjectIdUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli-login'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/onboarding'
    | '/api-keys'
    | '/audit-log'
    | '/credentials'
    | '/members'
    | '/projects/$projectId'
    | '/account/'
    | '/projects/'
    | '/settings/'
    | '/projects/$projectId/'
    | '/projects/$projectId/builds/$buildId'
    | '/projects/$projectId/channels/$channelId'
    | '/projects/$projectId/branches/'
    | '/projects/$projectId/builds/'
    | '/projects/$projectId/channels/'
    | '/projects/$projectId/environment-variables/'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli-login'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/onboarding'
    | '/api-keys'
    | '/audit-log'
    | '/credentials'
    | '/members'
    | '/account'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/builds/$buildId'
    | '/projects/$projectId/channels/$channelId'
    | '/projects/$projectId/branches'
    | '/projects/$projectId/builds'
    | '/projects/$projectId/channels'
    | '/projects/$projectId/environment-variables'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/updates'
  id:
    | '__root__'
    | '/_authed'
    | '/cli-login'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/_authed/_app'
    | '/_authed/onboarding'
    | '/_authed/_app/api-keys'
    | '/_authed/_app/audit-log'
    | '/_authed/_app/credentials'
    | '/_authed/_app/members'
    | '/_authed/_app/'
    | '/_authed/_app/projects/$projectId'
    | '/_authed/_app/account/'
    | '/_authed/_app/projects/'
    | '/_authed/_app/settings/'
    | '/_authed/_app/projects/$projectId/'
    | '/_authed/_app/projects/$projectId/builds/$buildId'
    | '/_authed/_app/projects/$projectId/channels/$channelId'
    | '/_authed/_app/projects/$projectId/branches/'
    | '/_authed/_app/projects/$projectId/builds/'
    | '/_authed/_app/projects/$projectId/channels/'
    | '/_authed/_app/projects/$projectId/environment-variables/'
    | '/_authed/_app/projects/$projectId/settings/'
    | '/_authed/_app/projects/$projectId/updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  CliLoginRoute: typeof CliLoginRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cli-login': {
      id: '/cli-login'
      path: '/cli-login'
      fullPath: '/cli-login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app/': {
      id: '/_authed/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/members': {
      id: '/_authed/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedAppMembersRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/credentials': {
      id: '/_authed/_app/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AuthedAppCredentialsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/audit-log': {
      id: '/_authed/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthedAppAuditLogRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/api-keys': {
      id: '/_authed/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthedAppApiKeysRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/settings/': {
      id: '/_authed/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedAppSettingsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/projects/': {
      id: '/_authed/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthedAppProjectsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/account/': {
      id: '/_authed/_app/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAppAccountIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/projects/$projectId': {
      id: '/_authed/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/projects/$projectId/': {
      id: '/_authed/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
    '/_authed/_app/projects/$projectId/updates/': {
      id: '/_authed/_app/projects/$projectId/updates/'
      path: '/updates'
      fullPath: '/projects/$projectId/updates/'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdUpdatesIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
    '/_authed/_app/projects/$projectId/settings/': {
      id: '/_authed/_app/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
    '/_authed/_app/projects/$projectId/environment-variables/': {
      id: '/_authed/_app/projects/$projectId/environment-variables/'
      path: '/environment-variables'
      fullPath: '/projects/$projectId/environment-variables/'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdEnvironmentVariablesIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
    '/_authed/_app/projects/$projectId/channels/': {
      id: '/_authed/_app/projects/$projectId/channels/'
      path: '/channels'
      fullPath: '/projects/$projectId/channels/'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdChannelsIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
    '/_authed/_app/projects/$projectId/builds/': {
      id: '/_authed/_app/projects/$projectId/builds/'
      path: '/builds'
      fullPath: '/projects/$projectId/builds/'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdBuildsIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
    '/_authed/_app/projects/$projectId/branches/': {
      id: '/_authed/_app/projects/$projectId/branches/'
      path: '/branches'
      fullPath: '/projects/$projectId/branches/'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdBranchesIndexRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
    '/_authed/_app/projects/$projectId/channels/$channelId': {
      id: '/_authed/_app/projects/$projectId/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/projects/$projectId/channels/$channelId'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdChannelsChannelIdRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
    '/_authed/_app/projects/$projectId/builds/$buildId': {
      id: '/_authed/_app/projects/$projectId/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/projects/$projectId/builds/$buildId'
      preLoaderRoute: typeof AuthedAppProjectsProjectIdBuildsBuildIdRouteImport
      parentRoute: typeof AuthedAppProjectsProjectIdRoute
    }
  }
}

interface AuthedAppProjectsProjectIdRouteChildren {
  AuthedAppProjectsProjectIdIndexRoute: typeof AuthedAppProjectsProjectIdIndexRoute
  AuthedAppProjectsProjectIdBuildsBuildIdRoute: typeof AuthedAppProjectsProjectIdBuildsBuildIdRoute
  AuthedAppProjectsProjectIdChannelsChannelIdRoute: typeof AuthedAppProjectsProjectIdChannelsChannelIdRoute
  AuthedAppProjectsProjectIdBranchesIndexRoute: typeof AuthedAppProjectsProjectIdBranchesIndexRoute
  AuthedAppProjectsProjectIdBuildsIndexRoute: typeof AuthedAppProjectsProjectIdBuildsIndexRoute
  AuthedAppProjectsProjectIdChannelsIndexRoute: typeof AuthedAppProjectsProjectIdChannelsIndexRoute
  AuthedAppProjectsProjectIdEnvironmentVariablesIndexRoute: typeof AuthedAppProjectsProjectIdEnvironmentVariablesIndexRoute
  AuthedAppProjectsProjectIdSettingsIndexRoute: typeof AuthedAppProjectsProjectIdSettingsIndexRoute
  AuthedAppProjectsProjectIdUpdatesIndexRoute: typeof AuthedAppProjectsProjectIdUpdatesIndexRoute
}

const AuthedAppProjectsProjectIdRouteChildren: AuthedAppProjectsProjectIdRouteChildren =
  {
    AuthedAppProjectsProjectIdIndexRoute: AuthedAppProjectsProjectIdIndexRoute,
    AuthedAppProjectsProjectIdBuildsBuildIdRoute:
      AuthedAppProjectsProjectIdBuildsBuildIdRoute,
    AuthedAppProjectsProjectIdChannelsChannelIdRoute:
      AuthedAppProjectsProjectIdChannelsChannelIdRoute,
    AuthedAppProjectsProjectIdBranchesIndexRoute:
      AuthedAppProjectsProjectIdBranchesIndexRoute,
    AuthedAppProjectsProjectIdBuildsIndexRoute:
      AuthedAppProjectsProjectIdBuildsIndexRoute,
    AuthedAppProjectsProjectIdChannelsIndexRoute:
      AuthedAppProjectsProjectIdChannelsIndexRoute,
    AuthedAppProjectsProjectIdEnvironmentVariablesIndexRoute:
      AuthedAppProjectsProjectIdEnvironmentVariablesIndexRoute,
    AuthedAppProjectsProjectIdSettingsIndexRoute:
      AuthedAppProjectsProjectIdSettingsIndexRoute,
    AuthedAppProjectsProjectIdUpdatesIndexRoute:
      AuthedAppProjectsProjectIdUpdatesIndexRoute,
  }

const AuthedAppProjectsProjectIdRouteWithChildren =
  AuthedAppProjectsProjectIdRoute._addFileChildren(
    AuthedAppProjectsProjectIdRouteChildren,
  )

interface AuthedAppRouteChildren {
  AuthedAppApiKeysRoute: typeof AuthedAppApiKeysRoute
  AuthedAppAuditLogRoute: typeof AuthedAppAuditLogRoute
  AuthedAppCredentialsRoute: typeof AuthedAppCredentialsRoute
  AuthedAppMembersRoute: typeof AuthedAppMembersRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppProjectsProjectIdRoute: typeof AuthedAppProjectsProjectIdRouteWithChildren
  AuthedAppAccountIndexRoute: typeof AuthedAppAccountIndexRoute
  AuthedAppProjectsIndexRoute: typeof AuthedAppProjectsIndexRoute
  AuthedAppSettingsIndexRoute: typeof AuthedAppSettingsIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppApiKeysRoute: AuthedAppApiKeysRoute,
  AuthedAppAuditLogRoute: AuthedAppAuditLogRoute,
  AuthedAppCredentialsRoute: AuthedAppCredentialsRoute,
  AuthedAppMembersRoute: AuthedAppMembersRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppProjectsProjectIdRoute: AuthedAppProjectsProjectIdRouteWithChildren,
  AuthedAppAccountIndexRoute: AuthedAppAccountIndexRoute,
  AuthedAppProjectsIndexRoute: AuthedAppProjectsIndexRoute,
  AuthedAppSettingsIndexRoute: AuthedAppSettingsIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  CliLoginRoute: CliLoginRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
