/**
 * Regenerates the pass-through modules in `packages/ui/src/components/` that
 * re-export Kumo's granular entrypoints under `@better-update/ui/components/*`.
 *
 *   bun run ui:gen
 *
 * Add a component to the lists below rather than hand-writing the file, so
 * every entrypoint keeps importing granularly — the `@cloudflare/kumo` barrel
 * drags charts, maps and shiki into whatever chunk touches it.
 *
 * The generated files are lint-exempt; a hand-written neighbour has to be named
 * in the negations in `packages/ui/oxlint.config.ts` to stay linted.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const OUT = join(import.meta.dirname, "..", "packages", "ui", "src", "components");

/** Styled Kumo components. */
const COMPONENTS = [
  "autocomplete",
  "badge",
  "banner",
  "breadcrumbs",
  "button",
  "chart",
  "checkbox",
  "clipboard-text",
  "code",
  "collapsible",
  "combobox",
  "command-palette",
  "date-picker",
  "dropdown",
  "empty",
  "flow",
  "grid",
  "input",
  "input-group",
  "label",
  "layer-card",
  "link",
  "loader",
  "menubar",
  "meter",
  "pagination",
  "popover",
  "radio",
  "select",
  "sensitive-input",
  "sidebar",
  "surface",
  "switch",
  "table-of-contents",
  "tabs",
  "text",
  "toolbar",
  "tooltip",
];
// `avatar`, `card`, `date-range-picker`, `dialog`, `field`, `item`, `kbd`,
// `separator`, `skeleton`, `table` and `toast` are deliberately absent: all
// eleven are hand-written. Kumo has no avatar, no list row (`LayerCard` is the
// nearest surface, and its card padding is wrong for a row that repeats down a
// page) and no keycap (its menu `Shortcut` is bare dimmed text). Its own
// `DateRangePicker` keeps the range in local state with no way to seed or read
// it, so ours composes the controlled calendar behind it instead. It ships no
// default toast
// manager and no `toast.success` / `toast.error` sugar, its `Field` takes only
// the structured error shape its `Input` normalizes, its `Dialog` is the bare
// popup — no header, footer, dismiss control or padding — its `Table` leaves
// the scroll container and the row hover to the caller, its `Separator` is Base
// UI's unstyled primitive (a zero-height element until someone draws the rule),
// it has no block placeholder at all (`SkeletonLine` is a fixed-height text line
// of random width, which SSR cannot hydrate), and `card` is the app's
// header/content/footer anatomy composed over the bare `LayerCard` surface
// generated above.

/** Base UI primitives Kumo re-exports without styling them. */
const PRIMITIVES = ["scroll-area", "toggle", "toggle-group"];

const moduleSource = (source: string): string =>
  [
    "// Generated by scripts/gen-kumo-passthrough.ts — do not edit.",
    "// Re-exported granularly: importing the `@cloudflare/kumo` barrel pulls",
    "// charts, maps and shiki into every chunk (~594 kB).",
    `export * from "${source}";`,
    "",
  ].join("\n");

const write = async (name: string, kind: "components" | "primitives"): Promise<void> => {
  await writeFile(join(OUT, `${name}.tsx`), moduleSource(`@cloudflare/kumo/${kind}/${name}`));
};

await mkdir(OUT, { recursive: true });
await Promise.all([
  ...COMPONENTS.map(async (name) => write(name, "components")),
  ...PRIMITIVES.map(async (name) => write(name, "primitives")),
]);

console.log(`wrote ${COMPONENTS.length + PRIMITIVES.length} pass-through modules`);
