/**
 * Regenerates the pass-through modules in `packages/ui/src/components/` that
 * re-export Kumo's granular entrypoints under `@better-update/ui/components/*`.
 *
 *   bun run ui:gen
 *
 * Add a component to the lists below rather than hand-writing the file, so
 * every entrypoint keeps importing granularly — the `@cloudflare/kumo` barrel
 * drags charts, maps and shiki into whatever chunk touches it.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const OUT = join(import.meta.dirname, "..", "packages", "ui", "src", "components");

/** Styled Kumo components. */
const COMPONENTS = [
  "autocomplete",
  "badge",
  "banner",
  "breadcrumbs",
  "button",
  "chart",
  "checkbox",
  "clipboard-text",
  "code",
  "collapsible",
  "combobox",
  "command-palette",
  "date-picker",
  "dialog",
  "dropdown",
  "empty",
  "field",
  "flow",
  "grid",
  "input",
  "input-group",
  "label",
  "layer-card",
  "link",
  "loader",
  "menubar",
  "meter",
  "pagination",
  "popover",
  "radio",
  "select",
  "sensitive-input",
  "sidebar",
  "switch",
  "table",
  "table-of-contents",
  "tabs",
  "text",
  "toast",
  "toolbar",
  "tooltip",
];

/** Base UI primitives Kumo re-exports without styling them. */
const PRIMITIVES = ["scroll-area", "separator", "toggle", "toggle-group"];

const moduleSource = (source: string): string =>
  [
    "// Generated by scripts/gen-kumo-passthrough.ts — do not edit.",
    "// Re-exported granularly: importing the `@cloudflare/kumo` barrel pulls",
    "// charts, maps and shiki into every chunk (~594 kB).",
    `export * from "${source}";`,
    "",
  ].join("\n");

const write = async (name: string, kind: "components" | "primitives"): Promise<void> => {
  await writeFile(join(OUT, `${name}.tsx`), moduleSource(`@cloudflare/kumo/${kind}/${name}`));
};

await mkdir(OUT, { recursive: true });
await Promise.all([
  ...COMPONENTS.map(async (name) => write(name, "components")),
  ...PRIMITIVES.map(async (name) => write(name, "primitives")),
]);

console.log(`wrote ${COMPONENTS.length + PRIMITIVES.length} pass-through modules`);
